Emit compiler errors for unknown field attributes
Emit an error if an unknown field attribute is used on a
`salsa::tracked` struct. For example, when changing the `return_ref`
attribute in `ParsedFile` to `returns_ref`, the compiler emits:

    error: unrecognized field attribute
       --> examples/lazy-input/main.rs:164:5
        |
    164 |     #[returns_ref]
        |     ^^^^^^^^^^^^^^